services:
  notify:
    image: ghcr.io/palomino79/notifier:latest
    volumes:
      - ./schedule/schedule.yml:/schedule.yml
    environment:
      SCHEDULE_PATH: "/schedule.yml"
      PUSH_SERVICE_URL: "http://ntfy"
      TOPIC: "generic-alerts"
      TEST_ON_START: True
