services:
  notify:
    build:
      context: .
      dockerfile: Dockerfile
    image: notify-service:local
    volumes:
      - ./:/app:ro
      - ./test_schedule/schedule.yml:/schedule.yml
    environment:
      SCHEDULE_PATH: "/schedule.yml"
      PUSH_SERVICE_URL: "https://ntfy.dont.panic"
      TOPIC: "birthday-alerts"
